backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{name}}”'
    update: 'Update {{collection}} “{{name}}”'
    delete: 'Delete {{collection}} “{{name}}”'

media_folder: "static/uploads"

collections:
  - name: "project"
    label: "Project"
    folder: "src/pages/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Project title", name: "title", widget: "string", required: true, default: "Project"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Github URL", name: "giturl", widget: "string", required: true}
      - {label: "Live URL", name: "liveurl", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: true}