backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'

media_folder: "static/uploads"

collections:
  - name: "project"
    label: "Project"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Project title", name: "title", widget: "string", required: true, default: "Project"}
      - {label: "Github URL", name: "giturl", widget: "string", required: true}
      - {label: "Live URL", name: "liveurl", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: true}